### PR TITLE
Download subjects

### PR DESCRIPTION
**Pull request by andrew**
Starting to spike out some work on the big one, downloading subjects, also known as #4, starting with the state of the issue/pull request:

screen shot 2017-05-11 at 9 59 48 pm

This opens the door to fixing/closing lots of the frequent requests we have on the issue tracker.

My plan is to store one copy of each subject (Issue, PR, Commit comment etc) and have it referenced from the notification so the data stays as fresh as possible without having to sync everything all the time. 

Current implementation loads issue/pr status on demand (very slow) and only for open source repos, lots still to do here, namely:

- [ ] decide on the data we want to store and be able to query against for each subject type (`RepositoryInvitation`, `Issue`, `PullRequest`, `Commit` and `Release`
- [ ] Cache the relevant subject info into a database table
- [ ] Sync the subject for each new/updated notification
- [ ] Decide on the permissions model and extra opt-in oauth scopes that will be required for this to work for private repos

### CODE REVIEW

**Comment by andrew** [comment]
@chrisarcand probably can merge your pr in here too: https://github.com/octobox/octobox/pull/326

**Comment by chrisarcand** [comment]
Yaaaasss 👍 

Will do.

**Comment by ForbesLindesay** [comment]
Please can you merge this?  I really want this.

**Comment by chrisarcand** [comment]
@ForbesLindesay Sadly this just isn't ready yet. I worked on it a far amount last week but there's much more to do. Keeping subjects in sync sanely with Github on users' requests (and limits) isn't quite as trivial as one might think.

If it's authors on issues you're looking for, you're welcome to deploy the version I currently use yourself: https://github.com/octobox/octobox/compare/master...chrisarcand:add-author

Note that I won't be writing a migration path from the above version to what should actually be merged in to master.

**Comment by ForbesLindesay** [comment]
It's the open/closed status I really need.  I'll do my best to wait patiently. Let me know if you need any JavaScript/html/etc. help. My Ruby's a little rusty.

**Comment by andrew** [comment]
Closing this in favour of https://github.com/octobox/octobox/pull/411, getting close to shipping it now 🚢

**Comment by andrew** [comment]
First part of this has been merged in #411 and is available behind the `FETCH_SUBJECT` env var feature flag, docs here: https://github.com/octobox/octobox/blob/master/INSTALLATION.md#downloading-subjects

Still working on getting it available on https://octobox.io

**Pull request closed without merging**
