### PR TITLE
Perform initial sync of subjects using an installation token

### LINKED ISSUE #1125: Repo which added Github Repo has some new features but not others
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
the Microsoft/vscode-docs now has the GitHub app installed to it, and it has the status as you can choose the filter of open/closed/merged, but as seen in the screenshot below, the icon is still black and I don't see the PR author:

screen shot 2018-10-19 at 8 34 05 am

Here's the PR for reference in the screenshot: https://github.com/Microsoft/vscode-docs/pull/2022

### PR DESCRIPTION
**Pull request by andrew**
Fixes #1125

There was an interesting race condition where the GitHub App was installed on a repository and the background job fired before any users had authorized the GitHub App oauth.

This meant there wasn't an app_token to download the subjects for existing notifications. 

Instead we kick off a sync of all possible subjects for a repository using an installation token which doesn't require any users to have authorized the GitHub App.

### CODE REVIEW

**Comment by pradyunsg** [comment]
I think this happened on my personal instance too but I wasn't sure if this was because of some mistake by me in configuration or a race condition like the description describes.

Would this result in a few notifications not syncing subjects and other details, despite having that enabled via the environment variable? They've still not synced their details FWIW.

**Comment by andrew** [comment]
@pradyunsg are you running your instance as a GitHub app?

**Comment by pradyunsg** [comment]
Yes, I'd enabled it day before, when I hit rate limits because I had ~1000 unread notifications. 🙈

That's when this happened. I've disabled the GitHub app since but those notifications haven't synced information since.

**Comment by andrew** [comment]
Downgrading an installation from a GitHub App back to just GitHub Oauth isn't a path that I've tested, I wonder if your user account record still has stuff in `app_token` or the repository records still has something in `app_installation_id`  which is screwing with things.

**Comment by andrew** [comment]
Might be worth deleting some of the synced data and redownloading it using your oauth token, commands to run in the console:

```ruby
AppInstallation.delete_all
Repository.delete_all
Subject.delete_all
Notification.subjectable.find_each{|n| n.update_subject(true); print '.' }
```
```

**Comment by pradyunsg** [comment]
```
Loading production environment (Rails 5.2.1)
irb(main):001:0> AppInstallation.delete_all
=> 1
irb(main):002:0> Repository.delete_all
=> 117
irb(main):003:0> Subject.delete_all
=> 2473
irb(main):004:0> Notification.subjectable.find_each{|n| n.update_subject(true); print '.' }
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................=> nil
irb(main):005:0>
```

Hmm... I seem to have lost all the metadata now but it's not got any subject information. IIUC, that's what the last line was supposed to do. :/

screenshot 2018-11-13 at 9 32 01 pm

**Comment by andrew** [comment]
Can help debug further tomorrow, launching on the marketplace in 45 mins 🎉

**Comment by pradyunsg** [comment]
No hurries. :)

**Comment by andrew** [comment]
@pradyunsg sounds weird but have you tried deleting your account from your install and then signing up again?

**Comment by pradyunsg** [comment]
I'll go ahead and do that... :(

**Comment by pradyunsg** [comment]
Oh, LOL. I've hit the rate limit for this hour and it's 3am. I'll take a look tomorrow.

**Pull request merged**
