### PR TITLE
Solution for different colours for different repos

### PR DESCRIPTION
**Pull request by RebeccaAR**
Solution for colour coding different repos/projects 

#1304

### CODE REVIEW

**Comment by RebeccaAR** [comment]
image

here you go :)

**Comment by andrew** [comment]
cc @benoittgt 👆

**Comment by benoittgt** [comment]
Thanks a lot!

**Comment by BenJam** [comment]
Firstly, thanks for putting this together @RebeccaAR. And apologies for the delay in getting around to this, December was mosly given over to holiday and getting the report for sustainoss.org drafted. 

As is I'm not really a fan of this solution as it leaves colour to chance and can end up with some quite horrid results:

image

I hear the issue from @benoittgt though. I just wonder whether there's another approach here. I'll pick up in #1304.

**Comment by BenJam** [comment]
@RebeccaAR I've presented a simple alternative in https://github.com/octobox/octobox/issues/1304#issuecomment-453543414 if you'd like to have another quick go. Else I may take it up Monday.

**Pull request closed without merging**
