### PR TITLE
Sync subject assignees and allow filtering by assignee

### LINKED ISSUE #722: Sync subject assignees
It'd be great to be able to filter and search notifications by issues assigned to you, I think all we need to save is an array of usernames on the subject from the `assignees` field on the [issues api](https://developer.github.com/v3/issues/#get-a-single-issue).

### PR DESCRIPTION
**Pull request by andrew**
Fixes #722, also related to https://github.com/octobox/octobox/pull/752

screen shot 2018-08-09 at 10 13 18

Sidebar menu item defaults to "Assigned to you", where "you" is the current logged in user, but the url param contains the current users login, i.e `octobox.io/?assignee=andrew`, so you can filter by issues/prs assigned to other users by manually change the url and in future the [advanced search](https://github.com/octobox/octobox/issues/742).

## TODO

- [x] Figure out if/how to also support mysql
- [x] Add a way to resync existing subjects to add assignee data

### CODE REVIEW

**Comment by andrew** [comment]
Ah, I forgot about mysql, this uses a postgresql only feature 😬

**Comment by andrew** [comment]
If you want to try this out on you're local instance, you'll currently need to delete and resync all subjects, run these two commands in the `$ rails console`:

```ruby

Subject.delete_all
Notification.subjectable.without_subject.find_each{|n| n.send(:update_subject) }
```

**Comment by BenJam** [comment]
LGTM (on postgres)

**Comment by andrew** [comment]
Now grouped with unlabelled and bot filters:

screen shot 2018-08-13 at 09 44 22

**Comment by andrew** [comment]
Also just confirmed that https://github.com/octobox/octobox/pull/756#issuecomment-412444522 happens here too, the only time you'll automatically pull in assignee changes is if you got assigned to it by someone else (although unassigning you by someone else doesn't trigger the same thing)

**Comment by andrew** [comment]
@jules2689 any ideas on how to make this mysql friendly? Storing the array with a serializer would be fine but I'm not sure of a way we can do a sql query to find all the subjects with a certain assignee in the array.

**Comment by jules2689** [comment]
json type? https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_json-arrayagg

**Comment by andrew** [comment]
JSON type for mysql was ok but was really painful to work with in PostgreSQL, instead opted to just serialise the logins into a string column manually.

**Comment by jules2689** [comment]
what's the potential downsides here? perf?

**Comment by andrew** [comment]
With an index there shouldn’t be a performance hit, biggest downside is the non-standard rails code but that can be hidden away in a serializer

**Pull request merged**
