### PR TITLE
Use git-merge icon for merged pull requests to match GitHub behaviour

### PR DESCRIPTION
**Pull request by andrew**
screen shot 2018-08-21 at 16 34 43

### CODE REVIEW

**Comment by andrew** [comment]
I wonder how much gymnastics we'd need to do to get the ["reopened"](https://octicons.github.com/icon/issue-reopened/) issue icon working

**Comment by pradyunsg** [comment]
A fair bit.

That'd probably need to fetch histories of the issue incrementally to determine if it'd been closed at some point in the past and is currently open. You can probably get granular with the GraphQL API to specifically fetch the needed information.

We would still need to filter/iterate through the events --  neither the REST API nor the GraphQL API provide the ability to do so. This would be a lot of queries for a long issue that's been closed for a while. This'd probably quickly eat into the rate limit too.

A testing query (note: all of the issues that show up are closed but that's not the point)

```graphql
query ($repo: String!, $user: String!) {
  repository (name: $repo, owner: $user) {
    issues (first: 10, states: CLOSED, orderBy: { direction: DESC, field: UPDATED_AT} ) {
      nodes {
        number
        timeline (last: 10) {
          nodes {
             ... on ClosedEvent {
              createdAt
            } 
          }
        }
      }
    }
  }
}
```

(for pypa, pip --> for 5447, a closed event doesn't show up in these last 10 events on the timeline, but it definitely is closed)

**Comment by andrew** [comment]
Doesn't look like GitHub actually uses the reopened icon anywhere either (just closed and reopened https://github.com/octobox/octobox/issues/813 to test):

Issues list:
screen shot 2018-08-21 at 17 17 49

Dashboard beta:
screen shot 2018-08-21 at 17 18 32

**Comment by pradyunsg** [comment]
I'm not sure it lists all the events though: https://api.github.com/repos/pypa/pip/issues/988/events

**Comment by andrew** [comment]
@pradyunsg it's paginated: https://api.github.com/repos/pypa/pip/issues/988/events?per_page=100&page=2

**Comment by pradyunsg** [comment]
Oh, right. The following is valid then:

> We would still need to filter/iterate through the events -- neither the REST API nor the GraphQL API provide the ability to do so. This would be a lot of queries for a long issue that's been closed for a while. This'd probably quickly eat into the rate limit too.

I guess one workaround would be to store "I-saw-till" for the timeline that Octobox has seen on an issue/PR, but that'd still mean a lot of requests during the initial sync I guess.

**Comment by andrew** [comment]
@pradyunsg excellent, let's push that over towards https://github.com/octobox/octobox/pull/709 as it's going to end up syncing the whole event timeline for issues

**Comment by pradyunsg** [comment]
Sounds good to me. :)

**Pull request merged**
