### PR TITLE
Initial support for filtering issues by labels

### PR DESCRIPTION
**Pull request by natemcmaster**
Initial implementation for #422. 

Preview:
 - Labels render in the subject line using the same colors set on GitHub
image
 - Labels are clickable. When clicked, they link to adding a filter for that label
image

Needs more automated tests, but didn't know what kind of coverage you expect from new features.

Side note: I've never written code with Ruby on Rails, so don't feel bad to tell me if I've royally messed up something here.

cc @chrisarcand

### CODE REVIEW

**Comment by natemcmaster** [comment]
Ping! Anyone out there?

**Comment by andrew** [comment]
Sorry for the delay in reviewing this, great work! 🚢

**Comment by natemcmaster** [comment]
Thanks @andrew!

**Comment by chrisarcand** [comment]
Yes indeed, great work @natemcmaster ! 💕 I've been pretty heads down at work lately so sorry I didn't get to circle back around on this.

**Comment by rhuss** [comment]
@natemcmaster thanks a lot, it's really a feature I desperately looked for. Unfortunately I have a serious issue that every label is only fetched once --> #561 

Do you have any idea whether this is easy fixable ? (sorry, I'm a ruby noob, so I'm not of much help here)

**Comment by natemcmaster** [comment]
@rhuss I didn't have this issue when I built and tested this feature, but there were a bunch of changes between mid January and when this got merged last week. It's possible something changed between then that made this change not work the same way

**Comment by rhuss** [comment]
@natemcmaster thanks for the update and thanks for the contribution ;-) If I only would knew Ruby a bit better than I would try to dive into the issue more. 

In #561 @aslakknutsen found out that it's very likely an issue with a failed re-insert of an already existing label in the DB, leading to an unique constraint violation.

Let me check whether I can do something here (I really would love to have this feature, as we are working on a large mono-repo where everything is categorized with labels).

**Comment by chrisarcand** [comment]
@rhuss I've been keeping your issue in mind and plan on looking at it this week. I've been meaning to update my box to utilize the label support here but your issue has made me wary to try it until now, when I have some time :)

**Comment by chrisarcand** [comment]
Looks like @andrew already got to it in #575 🎉 🙇

**Pull request merged**
