### PR TITLE
Exclude tmp directory from RuboCop

### PR DESCRIPTION
**Pull request by jhsu802701**

### CODE REVIEW

**Comment by andrew** [comment]
Looks like this is causing a test failure in CI

**Comment by jhsu802701** [comment]
The error message in the Travis test is:
```
Error: Unsupported Ruby version 2.1 found in `TargetRubyVersion` parameter (in vendor/bundle/ruby/2.6.0/gems/rainbow-3.0.0/.rubocop.yml). 2.1-compatible analysis was dropped after version 0.58.
Supported versions: 2.2, 2.3, 2.4, 2.5, 2.6
RuboCop failed!
The command "RAILS_ENV=test bundle exec rake --trace rubocop db:migrate test:skip_visuals" exited with 1.
```

You could restart the process in Travis, or I can close this pull request, start a new branch, and submit a pull request.

**Comment by andrew** [comment]
Looks like it's related to this issue: https://github.com/rubocop-hq/rubocop/issues/6398#issuecomment-431898694

I think we need to add this to `.rubocop.yml`: https://github.com/dgmstuart/swing-out-london/commit/0a036591bcf80331f6fd3ca24d0e374aa451b454

**Comment by jhsu802701** [comment]
I added the vendor directory to the list of exempt directories.  This resolves the issue.

**Comment by andrew** [comment]
Thanks!

**Pull request merged**
