### PR TITLE
Add visual acceptance tests

### PR DESCRIPTION
**Pull request by BenJam**
I'd like to do some refactoring of the frontend scrolling/transitions, so I started at looking at Percy to do visual diffs. I also suspect that #709 will be refactored as a new panel rather than page, which means a lot more SPA-like activity and clicky-clicky testing 😅

Unfortunately the default `rack_test` driver for Capybara doesn't support window resizing which we need to simulate the sidebar (and future thread view) panel(s) so I had to use `:selinium` and `geckodriver` which adds overhead on installation and slows testing. 

I'm not sure what the best approach here should be but it feels like this might encumber those running Octobox locally... Thoughts?

### CODE REVIEW

**Comment by andrew** [comment]
If you move the visual tests to a separate folder inside the `test` directory, maybe called `test/visuals`, then you can run them on their own with `rake test:visuals` (or any other folder name like `rake test:models`)

Then we can change the default `rake` task to skip the visual tests but still have them run on travis.

**Comment by andrew** [comment]
Related: https://github.com/octobox/octobox/issues/268

**Comment by BenJam** [comment]
> It's alive! It's ALIVE! Muuhuhahha

**Comment by BenJam** [comment]
I think this is ready to merge.  The purpose here isn't to test the functionality (that's in the minitests) but to do visual diffing over on Percy to pick anything up that we might otherwise miss.

**Pull request merged**
