### PR TITLE
Implement refresh on refresh

### LINKED ISSUE #205: Refresh on refresh
The first thing I do every time I load https://octobox.io/ is to click the refresh button. Open to automating that `onload`?

### PR DESCRIPTION
**Pull request by WillAbides**
This gives the user an option to sync notifications every time the notifications page loads.

2017-01-02 at 1 41 pm

closes #205

### CODE REVIEW

**Comment by andrew** [comment]
I think this is a bit too heavy handed, every time you click on any link in the sidebar it's going to sync, will make the app feel incredibly slow when it's enabled right?

**Comment by WillAbides** [comment]
Yes it is a bit heavy-handed.  As was mentioned in #205, there's not a good, clean way to distinguish which loads should trigger a refresh.

One thing I considered is for sync to check last_synced_at and not trigger a new sync unless it has been at least a minute (or maybe more).  That still isn't ideal, but at least it keeps us from rapidly hitting the api when switching between filters.

**Comment by WillAbides** [comment]
@andrew:  Consider addbec03c7227c3415778b48b1004f9ec0635bad.  Now when you sync notifications through auto-load, it sets since=last_synced_at to speed things up.  As you noted in #125, this won't sync read status.  For that you will still need to click the spinner.

**Comment by andrew** [comment]
Closing this, reasoning here: https://github.com/octobox/octobox/issues/205#issuecomment-270030067

**Pull request closed without merging**
