### PR TITLE
Use repo icon for visual aid on sidebar

### PR DESCRIPTION
**Pull request by tarebyte**
screen shot 2016-12-23 at 11 10 31

/cc @briannelson

### CODE REVIEW

**Comment by andrew** [comment]
I wonder if it makes sense to only group by org when there are more than one repo to show? Not sure how the mix of orgs and repos would work though, might be more confusing

**Comment by tarebyte** [comment]
> I wonder if it makes sense to only group by org when there are more than one repo to show? Not sure how the mix of orgs and repos would work though, might be more confusing

I don't mind having it being grouped with only one, but that may just be me. I just thought it was weird to not have an icon.

**Comment by briannelson** [comment]
With the indentation, this looks pretty slick. Nice work.

octobox

**Comment by andrew** [comment]
Agreed it is weird without the icon

**Comment by andrew** [comment]
🚢

**Pull request merged**
