### PR TITLE
Updates styles and icons to more closely match new Github

### PR DESCRIPTION
**Pull request by briannelson**
HOT DAMN:

octobox

### CODE REVIEW

**Comment by briannelson** [comment]
Maybe we can lose "Octobox" in the navbar?

**Comment by tarebyte** [comment]
@briannelson could we maybe just invert the logo without the circle?

**Comment by briannelson** [comment]
I tried that @tarebyte. What do you think?

artboard

**Comment by tarebyte** [comment]
I like that better! But that may be just me 😄

**Comment by chrisarcand** [comment]
TBH I really dislike compared to the current design, especially the 90's hyperlinky blue and other blinding colors that were added 😕 I understand it's supposedly for accessibility. 

But ¯\_(ツ)_/¯ Up to @andrew 

Just critiquing the work at hand, I actually like your original circle logo instead of the invert.

**Comment by briannelson** [comment]
My problem with the invert is more of a brain-wiring issue. I think I'm wired to see envelopes as white and silhouettes as black, so when it gets inverted, it throws me. The inverted version reminds me of:

image

**Comment by briannelson** [comment]
@chrisarcand I hear you. My mind immediately went back to the 90s with the blue, but I'm getting used to it...a little. My goal was to present less of a visual leap between Github and Octobox, but we can easily kill this branch if it's too off-putting.

**Comment by chrisarcand** [comment]
@briannelson Yup I gotcha. I still prefer the old style since they shipped the new toolbar and stuff but it's just not worth caring that much about (I'm not one of those people that immediately ran to browser plugins to revert it :eyeroll: ), and I see your visual leap point :) I'm sure the Mark and the other Githubbers in this project will be thrilled!

+1 on the logo thing though. I think the invert just looks straight up awkward and the original design quite nice.

**Comment by andrew** [comment]
Loving the inverted logo ❤

The more it looks like @librariesio the better in my book 😉

**Comment by GiacomoLaw** [comment]
Love the black header!

**Comment by andrew** [comment]
@briannelson just fixed the merge conflicts here, is this good to merge or do you want to make any further changes?

**Comment by andrew** [comment]
Updated with latest changes:

screen shot 2017-05-04 at 10 19 30 pm

**Comment by andrew** [comment]
Unless anyone is incredibly against this, I'm going to 🚢  it tomorrow.

**Comment by briannelson** [comment]
Just realized I never replied to this! Sorry @andrew. We'll see what kind of response we get with the icon :)

**Pull request merged**
