### PR TITLE
Snooze notifications

### LINKED ISSUE #452: Snoozing notifications
Throwing this out there to see if anyone but me would find this interesting. 

I really like the snooze feature of Google Inbox to hide an email until tomorrow or next week, we could potentially do the same thing for notifications in Octobox.

### PR DESCRIPTION
**Pull request by andrew**
Bringing some of #1054, finishing it off and adding support for thread view, closes #452.

Current snoozing options are:

- 1 hour
- 1 day
- 1 week
- 1 month

Other options welcome, keeping in mind that timezones are a thing so I'd like to stick to relative time's for the initial ship to keep things simple.

Todo:

- [ ] One bug to fix with snoozing individual notifications
- [ ] Show snoozed time in thread header

Screenshots:

Screenshot 2019-05-27 at 22 10 15
Screenshot 2019-05-27 at 22 09 59
Screenshot 2019-05-27 at 22 10 19
Screenshot 2019-05-27 at 22 10 09

### CODE REVIEW

**Comment by choldgraf** [comment]
This would be a really nice feature :-)

In my experience, there's value in at least one amount of time in-between "1 day" and "1 week". E.g., usually if there's a PR open in a project I'll say "I like this, I'll merge it after a few days unless somebody else suggests we should wait". In moments like that I've often wished I could snooze the PR in Octobox so that it pops into my feed later on (it'd be even better if I could tag the issue w/ something like "merge")

my 2 cents!

**Comment by jni** [comment]
Three options that I found useful in Mailbox:

- Snooze until next week (ie always Monday regardless of what day today is)
- Snooze until [date/time] (you could have a pop-up calendar widget when that is clicked) (imho this is a must-have, since all other things can be implemented from this)
- (on mobile only) Snooze to desktop (ie disappears from the mobile view but reappears once you're on your computer)

**Comment by bitboxer** [comment]
Snooze till Monday morning would be nice if i am reading issues and see something work related on a weekend.

**Comment by BenJam** [comment]
> keeping in mind that timezones are a thing so I'd like to stick to relative time's for the initial ship to keep things simple.

++

**Comment by mmarchini** [comment]
@andrew would you be open to merge this if someone took over and fixed conflicts as well as anything else that is pending?

**Comment by andrew** [comment]
@mmarchini absolutely, that would be super handy

**Pull request closed without merging**
