### PR TITLE
Link to last comment

### LINKED ISSUE #323: Notifications don't link to the updated part
If I click on a notification, that I got because of a new comment on a PR/issue, I get lead to that PR/issue. I don't get lead directly to the new comment.

With GitHub's email or web notifications the link includes a fragment identifier, such as `#issuecomment-282543202`.

(For me this severely limits the utility of Omnibox, and I was surprised to not find an issue open for this already.)

### PR DESCRIPTION
**Pull request by chrisarcand**
Closes #323

Notification links now lead to the latest comment on the issue/commit if applicable. This is tracked by syncing the `latest_comment_url` attribute on the notifications endpoint.

Since comment anchors are being toyed with as well, also moves our url parsing stuff in to it's own testable thing.

Note this change doesn't even require repo scope, so this can be deployed on octobox.io immediately if you like 😃

### CODE REVIEW

**Comment by andrew** [comment]
Nice, I wonder if it would make it easier to test if you passed the `Octobox.config.*` bits into the parser?

**Comment by chrisarcand** [comment]
Not really any more difficult, but you're right, I guess I should probably ✨ inject those dependencies✨ , at least with defaults. 💙

**Comment by chrisarcand** [comment]
@andrew I'm happy with this now, used it all day today and added some tests.

**Comment by andrew** [comment]
Lovely work 👌

**Pull request merged**
