### PR TITLE
More fixes to get bootstrap 4 working

### PR DESCRIPTION
**Pull request by samjacobclift**
PR to https://github.com/octobox/octobox/pull/366

Still work in progress

A few issues still needed to sort out that I noticed

1) removal of `hidden-` css classes
2) Mobile menu

screen shot 2017-08-31 at 15 41 49

### CODE REVIEW

**Comment by andrew** [comment]
Should I merge this or keep it open?

**Comment by samjacobclift** [comment]
I'll try and fix the `hidden-*` issue then I think we can merge it

**Comment by samjacobclift** [comment]
Attached the screenshots its prob best to merge now if we are ok with it all 👍 

Desktop screenshot

screen shot 2017-09-03 at 19 05 43


Mobile gif
moible gif

**Comment by andrew** [comment]
Ready for merging?

**Comment by samjacobclift** [comment]
@andrew go for it

**Comment by chrisarcand** [comment]
😕  Man I really do like the way it currently is better, not as harsh as those dark greys. Sigh.

**Comment by samjacobclift** [comment]
@chrisarcand I think we can make it a bit lighter to look how it is now

**Comment by chrisarcand** [comment]
Oh hah, I didn't actually notice until now the target branch on this PR :) Forget my comment, I assume everything is still very much a work in progress.

I assume we'll get a little closer to the current clean looking style in #366 before we merge it 😄

**Comment by BenJam** [comment]
I'm going to pick this up today.

**Pull request merged**
