### PR TITLE
Option for open github issue in new tab

### PR DESCRIPTION
**Pull request by dsalahutdinov**
Closes https://github.com/octobox/octobox/issues/615

### CODE REVIEW

**Comment by andrew** [comment]
I think this would probably be better as an application level configuration rather than a user one, i.e. enable it for your own octobox setup via an environment variable

**Comment by dsalahutdinov** [comment]
Hi, @andrew !
Thanks for review. It will definitely better to have application level option. So I will change the code

**Comment by pradyunsg** [comment]
@dsalahutdinov Could you look into this?

**Comment by andrew** [comment]
Closing this in favor of configuring the option via an ENV variable: https://github.com/octobox/octobox/pull/888

**Pull request closed without merging**
