### PR TITLE
Upgrade rails to 6.0.0

### PR DESCRIPTION
**Pull request by andrew**
Preparing for rails 6 by testing out 6.0.0.rc1

### CODE REVIEW

**Comment by andrew** [comment]
Seeing weird errors in travis atm

**Comment by andrew** [comment]
Ready for review, may not actually merge this until 6.0.0 final is released though.

**Comment by andrew** [comment]
This is running without issue on https://octobox-andrew.herokuapp.com/ now 🎉

**Comment by BenJam** [comment]
🙌

**Comment by andrew** [comment]
Note to self: upgrade this to rc2 https://weblog.rubyonrails.org/2019/7/30/Rails-6-0-rc2-released/

**Comment by andrew** [comment]
Rails 6.0.0 final is out, so this can be updated and merged! https://weblog.rubyonrails.org/2019/8/15/Rails-6-0-final-release/

**Pull request merged**
