### PR TITLE
fixed #291 - add fixed white space between footer elements

### LINKED ISSUE #291: Footer license/copyright looks weird on big screens
screen shot 2017-01-24 at 9 33 29 am

Only just saw the updated footer on desktop, and the stretchy spacing looks really off on large screens.

Mostly leaving this issue to bug myself to fix it 😬

### PR DESCRIPTION
**Pull request by GiacomoLaw**
Here is a demo: http://codepen.io/GiacomoLaw/pen/OWQYBz

Hope this helps!

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
Going to improve this.

**Comment by WillAbides** [comment]
Instead of adding style to the html, I would recommend changing the [css here](https://github.com/octobox/octobox/blob/f04baafa5150218ff2c8f82014a4ca20249d63fb/app/assets/stylesheets/application.scss#L63-L84).  If the left and right sides need different formatting, you could split `.footer-data` into two classes `.footer-data-left` and `.footer-data-right`.

You may already know this, but you can use [chrome dev-tools](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/) preview css changes on the live page.  That can dramatically speed up workflow on design work.

**Comment by GiacomoLaw** [comment]
Just a quick question, does Ruby on Rails automatically refer to the stylesheet or do I have to add a link in the header myself?

**Comment by GiacomoLaw** [comment]
I presume it does seeing as there are no links.

**Comment by GiacomoLaw** [comment]
There you go, should work well.

**Comment by andrew** [comment]
@GiacomoLaw can you uses classes for left and right instead of ids?

**Comment by GiacomoLaw** [comment]
@andrew Sure, will do

**Comment by GiacomoLaw** [comment]
@andrew Done. :)

**Comment by GiacomoLaw** [comment]
I think it would be better if they were left as `ids`.

**Comment by andrew** [comment]
@GiacomoLaw I just checked this out locally, looks like changing the `.container` class breaks the homepage:

screen shot 2017-02-01 at 11 11 08 am

**Comment by GiacomoLaw** [comment]
Woops, let me just do something.

**Comment by GiacomoLaw** [comment]
Okay, I reverted it to id.

It should be displaying like this: http://codepen.io/GiacomoLaw/pen/OWQYBz

**Comment by GiacomoLaw** [comment]
Is that good? 😄

**Comment by chrisarcand** [comment]
@GiacomoLaw I hate to be a Git history purist (and usually don't mind some extra commits), but would you mind squashing these commits into one before this is merged? 8 commits in history before I get back to the one that specifies why this small change was done is just a little too much IMO :)

If you need help doing that, [Steve Klabnik has an excellent short reference](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request) showing how.

**Comment by andrew** [comment]
The .container class isn't specific enough and still breaks the homepage, needs to be scoped to just the footer

**Comment by GiacomoLaw** [comment]
Okay, will do. Is the .container class used elsewhere? I could just change the name to something else.

**Comment by GiacomoLaw** [comment]
I renamed the container class to a more specific name. Should that work now?

Thanks! 🙂

**Comment by andrew** [comment]
I changed the footer quite a bit in https://github.com/octobox/octobox/pull/346, going to close this one as I don't think it's relevant anymore

**Pull request closed without merging**
