### PR TITLE
Show the latest Git SHA in Settings

### LINKED ISSUE #503: Ability to see what version number of Octobox is running in the UI
Show current Octobox version number in the main UI.

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [x] My instance

🐞 **Problem**
I am currently running Octobox in a Docker image.  I "think" I have the most recent version running, but I have no real way of knowing if I am.  i.e. there is nothing displayed in the Octobox UI which says "Version x.x.x.".

🎯 **Goal**
I think it would be very useful to surface this information into the UI, as then there would be no ambiguity about what version is running on any given instance.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by lewispb**
Resolves #503 

Shows the latest Git SHA on the Settings page

screenshot-2017-12-24 octobox

### CODE REVIEW

**Comment by andrew** [comment]
Awesome, thanks! How does this handle there the case where no git directory is present?

**Comment by lewispb** [comment]
Good question! Apparently `Git.Open(dir)` raises an `ArgumentError`. I've solved this by rescuing and returning `nil`, but let me know if you'd prefer a different pattern.

**Comment by andrew** [comment]
LGTM 👍

**Comment by gep13** [comment]
@lewispb thanks for doing this!

**Pull request merged**
