### PR TITLE
Improved error pages

### PR DESCRIPTION
**Pull request by GiacomoLaw**
They were the defualt ones, so I cleaned them up a little.

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
I also added .htaccess

**Comment by andrew** [comment]
We don't need the .htaccess file, rails will render those files itself and pass them to the proxying web server

**Comment by GiacomoLaw** [comment]
Oh, okay. I'll remove it then.

**Comment by GiacomoLaw** [comment]
Done 😄

**Comment by andrew** [comment]
🎉

**Comment by GiacomoLaw** [comment]
Thank you!

**Pull request merged**
