### PR TITLE
Update to Ruby 2.4.1 (Part Deux)

### PR DESCRIPTION
**Pull request by chrisarcand**
Oops. This stuff should have been included in #349, sorry.

### CODE REVIEW

**Comment by chrisarcand** [comment]
😬

**Comment by andrew** [comment]
😬

**Comment by thiesschneider** [comment]
hm... since this release i cant access octobox. I am using Docker with jwilder nginx gen with --expose 3000. now there is a 502 bad gateway error.
any ideas?

**Comment by andrew** [comment]
@thiesschneider would you be able to open a new issue so it doesn't get lost here?

**Comment by andrew** [comment]
@thiesschneider I think it's related to this bug in puma: https://github.com/puma/puma/issues/1284, just testing with the previous version and will open a PR shortly if it works.

**Pull request merged**
