### PR TITLE
Per Page Picker Redo

### PR DESCRIPTION
**Pull request by briannelson**
Move this to the org repo instead of a fork

Copy of #139

### CODE REVIEW

**Comment by briannelson** [comment]
@tarebyte can you work your magic on *this* branch?

**Comment by andrew** [comment]
MOAR conflicts!

**Comment by briannelson** [comment]
@andrew fixed those conflicts but still haven't enabled per_page on the sync button or the new repo owner/repo links.

**Comment by andrew** [comment]
Just having a look at it now

**Comment by andrew** [comment]
@briannelson just pushed some tweaks, I think it's working as expected now

**Pull request merged**
