### PR TITLE
Per page picker

### LINKED ISSUE #132: Flexible page size
Currently the page size is hard coded as 20. 

Most users may want to have a better control over how many notifications are displayed per page. Some think like `page=2&per_page=50` so that the user can change the page size if they want to or resort to default of `20`.

### PR DESCRIPTION
**Pull request by briannelson**
Adds a per page picker to the inbox list

octobox

Closes #132

### CODE REVIEW

**Comment by briannelson** [comment]
The only issue I'm having is getting the per_page param to carry over when you press the sync button (currently it gets wiped).

I've built in the per_page param into all the other links, I think.

Any help is appreciated.

/cc @andrew @tarebyte

**Comment by tarebyte** [comment]
@briannelson that's because the sync is a post action and needs to be whitelisted in the strong params, I'll make that change for you.

**Comment by tarebyte** [comment]
@briannelson it doesn't look like I can't push to your branch so here's a diff of my changes.

This _should_ keep all of the filters regardless of what action you perform.

```diff
diff --git a/app/controllers/notifications_controller.rb b/app/controllers/notifications_controller.rb
index 33874ad..187e259 100644
--- a/app/controllers/notifications_controller.rb
+++ b/app/controllers/notifications_controller.rb
@@ -44,12 +44,12 @@ class NotificationsController < ApplicationController
     scope = scope.starred                         if archive_params[:starred].present?
 
     scope.update_all(archived: true)
-    redirect_to root_path
+    redirect_to root_path(post_notification_url_params)
   end
 
   def unarchive
     @notification.update_columns archived: false
-    redirect_to root_path(type: params[:type], repo: params[:repo], archive: true)
+    redirect_to root_path(post_notification_url_params.merge(archive: true))
   end
 
   def star
@@ -59,7 +59,7 @@ class NotificationsController < ApplicationController
 
   def sync
     current_user.sync_notifications
-    redirect_to root_path(type: params[:type], repo: params[:repo])
+    redirect_to root_path(post_notification_url_params)
   end
 
   private
@@ -73,7 +73,7 @@ class NotificationsController < ApplicationController
   end
 
   def archive_params
-    params.permit(:repo, :reason, :type, :status, :starred)
+    params.permit(:repo, :reason, :type, :status, :starred, :per_page)
   end
 
   def page
@@ -86,4 +86,15 @@ class NotificationsController < ApplicationController
     raise ActiveRecord::RecordNotFound if per_page > 100
     per_page
   end
+
+  def post_notification_url_params
+    {
+      repo:     archive_params[:repo],
+      reason:   archive_params[:reason],
+      type:     archive_params[:type],
+      status:   archive_params[:status],
+      starred:  archive_params[:starred],
+      per_page: archive_params[:per_page]
+    }
+  end
 end
diff --git a/app/views/notifications/index.html.erb b/app/views/notifications/index.html.erb
index 153eae7..0acf0b0 100644
--- a/app/views/notifications/index.html.erb
+++ b/app/views/notifications/index.html.erb
@@ -1,5 +1,7 @@
+<% url_params = { repo: params[:repo], reason: params[:reason], type: params[:type], status: params[:status], starred: params[:starred], per_page: params[:per_page] } %>
 <% no_url_filter_parameters_present = (params[:archive].nil? && params[:repo].nil? && params[:type].nil? && params[:status].nil? && params[:reason].nil?) %>
 
+
 <nav class="navbar navbar-default navbar-fixed-top">
   <div class="container-fluid">
     <!-- Brand and toggle get grouped for better mobile display -->
@@ -68,11 +70,9 @@
               <span class="caret"></span>
             </button>
             <ul class="dropdown-menu">
-              <li><%= link_to '20', root_path(per_page: 20, status: params[:status], type: params[:type], repo: params[:repo], archive: params[:archive]) %></li>
-              <li><%= link_to '40', root_path(per_page: 40, status: params[:status], type: params[:type], repo: params[:repo], archive: params[:archive]) %></li>
-              <li><%= link_to '60', root_path(per_page: 60, status: params[:status], type: params[:type], repo: params[:repo], archive: params[:archive]) %></li>
-              <li><%= link_to '80', root_path(per_page: 80, status: params[:status], type: params[:type], repo: params[:repo], archive: params[:archive]) %></li>
-              <li><%= link_to '100', root_path(per_page: 100, status: params[:status], type: params[:type], repo: params[:repo], archive: params[:archive]) %></li>
+              <% [20, 40, 60, 80, 100].each do |interval| %>
+                <li><%= link_to interval.to_s, root_path(per_page: interval, status: params[:status], type: params[:type], repo: params[:repo], archive: params[:archive]) %></li>
+              <% end %>
             </ul>
           </div>
 
@@ -80,23 +80,11 @@
             <%= octicon 'three-bars', :height => 16 %>
           </button>
 
-          <%= link_to sync_notifications_path(), class: 'btn btn-default sync', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'data-turbolinks' => false, 'data-animation' => 'false', 'data-position' => 'bottom', 'title' => 'Refresh list', method: :post do %>
+          <%= link_to sync_notifications_path(url_params), class: 'btn btn-default sync', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'data-turbolinks' => false, 'data-animation' => 'false', 'data-position' => 'bottom', 'title' => 'Refresh list', method: :post do %>
             <%= octicon 'sync', :height => 16 %>
           <% end %>
           <% if @notifications.any? && !params[:archive].present? %>
-            <%= link_to(
-                  (no_url_filter_parameters_present ? 'Archive all' : 'Archive this list'),
-                  archive_notifications_path(
-                    repo:    params[:repo],
-                    reason:  params[:reason],
-                    type:    params[:type],
-                    status:  params[:status],
-                    starred: params[:starred]
-                  ),
-                  class: 'btn btn-default',
-                  method: :post
-                )
-            %>
+            <%= link_to((no_url_filter_parameters_present ? 'Archive all' : 'Archive this list'), archive_notifications_path(url_params), class: 'btn btn-default', method: :post) %>
           <% end %>
           <%= render 'filter-list' %>
         </div>
```

**Comment by briannelson** [comment]
Ah sorry bout that. I'll make that change in the morning.

**Comment by andrew** [comment]
We can probably hide the drop down on small screens

**Comment by andrew** [comment]
I've added @briannelson as a collaborator so you can just make regular branches on this repo now, no need to fork 🏅

**Comment by andrew** [comment]
Moved to: https://github.com/octobox/octobox/pull/152

**Pull request closed without merging**
