### PR TITLE
added Bullet gem to detect N+1 queries and unused eager loading

### PR DESCRIPTION
**Pull request by prashuchaudhary**

### CODE REVIEW

**Comment by prashuchaudhary** [comment]
@andrew I want to add Bullet gem config to detect N+1 queries in DEV environment.

**Comment by andrew** [comment]
@prashuchaudhary tests appear to be broken here

**Comment by prashuchaudhary** [comment]
@andrew moved the Gems to only DEV group as they caught the errors. Tests are green now.

**Comment by andrew** [comment]
@prashuchaudhary awesome, I'm going to hold off merging this until @chrisarcand has finished his work on https://github.com/octobox/octobox/issues/927 so as not to suddenly enable bullet on everyone who's running octobox on docker in development mode.

**Comment by prashuchaudhary** [comment]
@andrew it won't be enabled as one need to set a ENV flag.

**Comment by andrew** [comment]
Oh yeah, good catch!

**Comment by chrisarcand** [comment]
Yup, looks good 👍

**Pull request merged**
