### PR TITLE
Added link to main contributor GitHub profile

### PR DESCRIPTION
**Pull request by GiacomoLaw**
I added a link to the GitHub profile to the main contributor so people knew where they could go to find more of the same dev.

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
Let me fix that...

**Comment by GiacomoLaw** [comment]
That should work now 😄

**Comment by GiacomoLaw** [comment]
Odd, it's returning this:

```
Failure:
ApplicationHelperTest#test_copyright_message_has_no_et_al_link_when_no_contributors_are_found [/home/travis/build/octobox/octobox/test/helpers/application_helper_test.rb:14]:
--- expected
+++ actual
@@ -1 +1 @@
-"© 2017 Andrew Nesbitt, et al"
+"© 2017 <a href='https://github.com/andrew' target='_blank'>Andrew Nesbitt</a>, et al"
```

But I've updated the `application_helper_test` with all the changes - it shouldn't be returning this error as far as I can see 😖

**Comment by andrew** [comment]
@GiacomoLaw took me a minute to spot the problem on GitHub but it showed up right away in my editor with syntax highlighting, you need to change line 14 of `application_helper_test` to put double quotes around the outer string like so:

    assert_equal "© 2017 <a href='https://github.com/andrew' target='_blank'>Andrew Nesbitt</a>, et al", copyright_message

**Comment by GiacomoLaw** [comment]
Ah, thanks. There you go, edited. Sorry! 😞

**Comment by andrew** [comment]
🎉

**Pull request merged**
