### PR TITLE
Style the checkboxes to be more consistent and easier to deal with ae…

### PR DESCRIPTION
**Pull request by prashuchaudhary**
…sthetically #792

### CODE REVIEW

**Comment by prashuchaudhary** [comment]
Screenshots of the Changes

screen shot 2018-10-05 at 2 00 15 pm
screen shot 2018-10-05 at 2 00 29 pm
screen shot 2018-10-05 at 2 01 06 pm
screen shot 2018-10-05 at 2 01 15 pm

**Comment by pradyunsg** [comment]
Could you make the border match the color of the star border?

**Comment by andrew** [comment]
@prashuchaudhary there's a couple visual tests that need updating too, you can run them with `rake test:visuals`

**Comment by prashuchaudhary** [comment]
@pradyunsg  matched color of border with star border

screen shot 2018-10-05 at 5 55 41 pm
screen shot 2018-10-05 at 5 55 59 pm

**Comment by pradyunsg** [comment]
I'm coming in late but perhaps adding the following would be nice:

```css
.custom-control {
    min-height: auto;
}
```

Current `master`:

screen shot 2018-10-09 at 10 12 24 pm

With the above snippet:

screen shot 2018-10-09 at 10 12 17 pm

It's subtle, but the row heights are reduced to better fit the content. It seems like the checkbox is by default taller than it actually needs to be. :/

(yes, I've styled the unread highlight to be more subtle)

**Comment by prashuchaudhary** [comment]
@pradyunsg cool. thanks for appreciating the effort.

**Pull request merged**
