### PR TITLE
Fix Open Collective rake task

### PR DESCRIPTION
**Pull request by BenJam**
- [x] Re-add removal of accounts
- [x] Add tests
- [x] Remove accounts that have lapsed

### CODE REVIEW

**Comment by BenJam** [comment]
@andrew just thinking about lapsed accounts: when does this script get run? I suspect I need to add the last-transaction date to `get_sub_names` and make sure that date+ 1 month is added as the `next_billing_date` on the corresponding subscription purchase.

**Comment by andrew** [comment]
It runs every hour I believe

**Comment by BenJam** [comment]
okay I remembered we filter out tx's at the first step, so I think this is good to go now.

**Comment by andrew** [comment]
👍 merge when ready

**Pull request merged**
