### PR TITLE
Fixes: #528. Fixed margin issues with table.

### PR DESCRIPTION
**Pull request by existentialmoron**
See #528 
I have added a media query for less than 768px and adjusted margin for width b/w 768px and 991px.

### CODE REVIEW

**Comment by andrew** [comment]
Thanks!

**Comment by existentialmoron** [comment]
Although this fixes the issue of hidden row, I notice now the table has unnecessarily large margin when the label is not applied. One way I can think of solving is this by adding a class to table or panel when there is a label added. That way, I can add different styling when label is there.

Unfortunately, I am unfamiliar with ruby on rails. @andrew  if you can point me where I need to make changes to add classes when label is added, I would be able to work this out.

**Comment by andrew** [comment]
@existentialmoron ah yeah, I didn't notice that initially.

To add a class if a filter has been applied here's the code: 

```erb
<%= 'filtered' if any_active_filters? %>
```

I think you'll want to add it in here: https://github.com/octobox/octobox/blob/2d1ded72be275f96e81002b32577a2e004c5da45/app/views/notifications/index.html.erb#L54

So it looks something like this:

```html
<table class='table table-hover table-notifications js-table-notifications <%= 'filtered' if any_active_filters? %>' data-refresh-interval=<%= current_user.effective_refresh_interval %>>
```

**Comment by existentialmoron** [comment]
@andrew 
I have made a pull #696 for this.
Kindly review :)

**Pull request merged**
