### PR TITLE
#1316 add slash shortcut to focus on search input

### LINKED ISSUE #1316: Slash ("/") should focus on "Search Box", not show the Help dialog (which is done by "?")
### What feature you'd like to see
The Slash ("/") button to focus on "Search Box"

## Motivation
Now, both the "/" and the "?" (which is "shift-/") keyboard shortcuts show the Help dialog. This is not needed and we lose the "/" for the "Search box".

## Pitch
In many other apps (like Gmail, Google Calendar, etc.) the "/" is the shortcut for the "Search Box".

### PR DESCRIPTION
**Pull request by evexoio**
fixes #1316

### CODE REVIEW

**Comment by andrew** [comment]
Great work, thanks for the pull request!

**Comment by evexoio** [comment]
@afilp Sure, can you please open an issue for it?

**Comment by afilp** [comment]
Here it is, thanks!
https://github.com/octobox/octobox/issues/1338

**Comment by evexoio** [comment]
@afilp Sure!

You created dupes tho, can you close https://github.com/octobox/octobox/issues/1337?

**Pull request merged**
