### PR TITLE
Advanced search queries

### LINKED ISSUE #742: Advanced search query syntax
Example:

`unread:true type:issue reason:mention owner:octobox repo:octobox/octobox label:bug free text`

Potential ruby gems we can use for parsing: https://github.com/marcelocf/searrrch

Other potential filters we can support:

- author
- assignee
- subject
- body (#709)
- comments (#709)
- date
- inbox/archive/starred
- team

This is also the first step in enabling custom filters, where if a notification comes in an matches a custom saved search then perform some action, useful for #8, #217 and #599

### PR DESCRIPTION
**Pull request by andrew**
Closes #742

screen shot 2018-08-12 at 22 23 37

Supported keywords:

- repo (octobox/octobox)
- owner (octobox)
- type (issue, pull request etc)
- reason (mention, author etc)
- label (if `FETCH_SUBJECT` enabled)
- state (open, closed, merged, if `FETCH_SUBJECT` enabled)
- starred (true/false)
- archived (true/false)
- unread (true/false)
- bot:true
- unlabelled:true

Also adds a small visual change in search results to show if a notification has been archived or not:

screen shot 2018-08-12 at 22 18 39

~n.b. related (existing) bug there, can't unarchive things from search results:~

screen shot 2018-08-12 at 22 20 09

Also doesn't highlight the inbox when showing search results (as we also show archived things by default):

screen shot 2018-08-12 at 22 19 00

Multiple, comma separated args aren't supported (`label:bug,design`) atm, hence singular names for all keywords.

No sorting included here either.

One other thing to consider, but probably doesn't need to be solved in this PR is if we turn the keywords into real filters, currently the UI doesn't know that when you search for `owner:octobox` that you're filtering by owner, so the UI looks like this:

screen shot 2018-08-12 at 22 25 00

rather than this:

screen shot 2018-08-12 at 22 25 09

Looking at how gmail does it's search/filtering, the UI does respond to keywords in search, i.e. `is:starred` highlights the starred sidebar item:

screen shot 2018-08-12 at 22 26 02

Also interesting there is that clicking on the `Starred` sidebar adds `is:starred` to the search box, which might be something for us to consider, although you can't click on multiple sidebar items to keep filtering down in gmail.

There's also slightly nasty hack to the `searrrch` gem to add support for `/`, `-` and `.` in filter values, I will attempt to contribute a patch back but it's not been touched 2 years so may not get merged.

TODO:

- [x] Replace searrrch hack
- [x] Docs
- [x] Tests

### CODE REVIEW

**Comment by andrew** [comment]
One other thing I suspect that won't work as expected is searching for emoji labels, as we store them as `:+1:` rather than the actual utf8 characters.

**Comment by pradyunsg** [comment]
How about completely getting rid of the "Filter:" section and switching to the search bar exclusively?

**Comment by andrew** [comment]
@pradyunsg interesting idea 🤔

**Comment by andrew** [comment]
Another couple of filters that can be added:

- bot:true
- unlabelled:true

And once https://github.com/octobox/octobox/pull/761 is merged:

- assigned:andrew

**Comment by andrew** [comment]
Another search filter that can be added one #781 is merged:

- private: true

**Comment by andrew** [comment]
I decided to vendor a simplified version of Searrrch as `SearchParser` because we're not using most of it's features/options.

**Comment by andrew** [comment]
I've added a search prefix cheat sheet modal to serve as documentation:

screen shot 2018-08-16 at 11 06 14

Accessible via a little `?` icon on the right of the search box:

screen shot 2018-08-16 at 11 47 32

**Comment by pradyunsg** [comment]
> I've added a search prefix cheat sheet modal to serve as documentation:

LGTM.

Minor styling suggestion: Instead of a banded table, have a plain one. It's be just as readable due to the ample padding to the content IMO.

**Comment by andrew** [comment]
@pradyunsg done!

**Comment by pradyunsg** [comment]
This still has the WIP label. :P

**Comment by andrew** [comment]
🚢 deploying this to https://octobox.io now!

**Comment by chrisarcand** [comment]
Sorry for the lack of eyes, I'm still on funemployment :) This looks *awesome*, nice work @andrew

**Comment by andrew** [comment]
@chrisarcand no worries, enjoy your time off!

**Pull request merged**
