### PR TITLE
Better design for threads status

### LINKED ISSUE #1336: Octobox issue view doesn't redirect to github when "Open" button is clicked
"Open" button in top of Octobox's issue view doesn't send to github issue url when "open" button is clicked.

Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**
dec-05-2018 17-43-30

🎯 **Goal**
Make "Open" Button send to github.

💡 **Possible solutions**
It might be a missing a tag with a href to the github issue or something

### PR DESCRIPTION
**Pull request by evexoio**
Closes #1336 

Replace thread status from button to badge.

**I can't test this locally** since I couldn't get an issue that is supported by octobox(they all redirect me to github)

**please test this before merging.**

### CODE REVIEW

**Comment by andrew** [comment]
Screenshots from testing:

Before:

screen shot 2018-12-17 at 11 58 26

After:

screen shot 2018-12-17 at 11 57 58

The icon is missing in all variations and the purple is gone from the merged variant:

screen shot 2018-12-17 at 11 58 53

ccing @BenJam as he originally worked on this view

**Comment by evexoio** [comment]
@BenJam Hey, I won't be able to work on this, my laptop's charger broke and I won't be able to get a new one anytime soon.

**Comment by BenJam** [comment]
No worries @evexoio I'll take a look shortly. Thanks for letting me know 👍

**Comment by BenJam** [comment]
looks like the sizing is tripping the reset.sss which carves out overflow of svg elements.

**Pull request closed without merging**
