### PR TITLE
Update the Octobox logo

### PR DESCRIPTION
**Pull request by BenJam**
* adds new 'infinitacle' logo svgs and pngs
* adds new octobox_round helper to add the logo to light surfaces
* attributes designer of original artwork in footer

Note: While I designed this logo it is a derivative of an illustration by Raeha Keller who authorised its use for Octobox.io What does this mean for the project? Discuss.

### CODE REVIEW

**Comment by BenJam** [comment]
Without wanting to go down a rabbit hole: we might want to supplant the current logo if not running at Octobox.io. But kind of side-steps the point about open licensing. In reality this is 🌩in a ☕️stuff.

**Comment by andrew** [comment]
We'll also need to update all the favicons listed in https://github.com/octobox/octobox/blob/master/app/views/layouts/_favicons.html.erb

**Comment by pradyunsg** [comment]
A minor nit - on FF+MacOS, it doesn't seem to be a transparent logo for the octobox.io.

**Comment by pradyunsg** [comment]
Can't post a SS, not on a laptop currently.

**Pull request merged**
