### PR TITLE
Set page to last if page number is too big

### LINKED ISSUE #166: Archiving all notifications on last page incorrectly tells you your octobox is open
#### To replicate:
1. Have at least 2 pages worth of notifications.
2. Go to last page.
3. Archive all notifications on that page.

#### What should happen:
Octobox should show the previous page (the new last page)

#### What happens:
Octobox shows a notification telling you: You're in the clear! There are no notifications that need your attention.

#### Easier way to replicate:
1. Visit https://octobox.io/?page=20000

_If this page still shows notifications... you have bigger problems than this bug to deal with._

### PR DESCRIPTION
**Pull request by karpiu**
Fixes #166

### CODE REVIEW

**Comment by andrew** [comment]
Can we redirect to the correct URL instead of changing the page number in the action?

**Comment by karpiu** [comment]
@andrew But that would mean recalculating everything in `index` action, right? Would it matter that much, performance-wise?

**Comment by karpiu** [comment]
@andrew Have you read my previous comment?

**Comment by andrew** [comment]
@karpiu just committed a tweaked version of this that redirects if the page is out of bounds: https://github.com/octobox/octobox/commit/544238b19077871d4fb8b6730abeef50d3042e0e

**Pull request closed without merging**
