### PR TITLE
Labels belong to repositories fixes ISSUE 818

### PR DESCRIPTION
**Pull request by prashuchaudhary**
# Part 1 - Task Breakdown

- [x] Create a new join table `SubjectLabel` for mapping Subject to Labels. 
- [x] Add Repository to Label table; associate is to Repository Model.
- [x] Start Inserting Data in SubjectLabel when we are association Label to Subject. Also, update repository mapping during this.
- [x] Create a rake task to `populate SubjectLabel table with the OLD DATA` and `Update mapping of Labels to Repository`. 
- [x] Move OLD code for associate Label to Subject into a separate module so that if we have to revert back if we only have to make some minor changes.
- [x] Fix existing test cases
- [x] Check Queries on Subject and Labels and Update if necessary
- [x] Write new test cases

 ### RAKE TASK 
 Rake task will find unique Label based on `GITHUB_ID` ordered by the `created_at ASC` and create a mapping between `Subject and Labels`. Also update the Label Repository Mapping.

# Part 2 - Will be tables cleanup.
- [ ] Cleanup OLD labels and Dropping the Subject Column will be done afterwards in case we have to revert back.

### CODE REVIEW

**Comment by andrew** [comment]
This is looking good, the slightly tricky part is going to be handling part 2 for users like @jules2689, @chrisarcand and @tarebyte who are going to be upgrading at a different rate to what I'll be doing on https://octobox.io

It might make sense to put the raw sql rake task as part of the migration so there's a nice atomic upgrade without depending on activerecord relation logic.

**Comment by andrew** [comment]
A related performance improvement I was thinking was to cache/denormalize the label name strings onto subjects so when filtering by a label string we can avoid joining across either the labels table (and after this, also joining across the repositories table)

**Comment by prashuchaudhary** [comment]
will move the code and create a migration for Updating the Subject Labels

**Comment by prashuchaudhary** [comment]
@andrew can you please review the changes?

 I have added test cases for all use cases and checked for existing behavior.

**Comment by andrew** [comment]
@prashuchaudhary looks like the tests are broken on mysql

**Comment by prashuchaudhary** [comment]
@andrew checking the tests.

**Comment by prashuchaudhary** [comment]
fixed the broken tests.

**Comment by prashuchaudhary** [comment]
fixes #818

**Comment by prashuchaudhary** [comment]
@andrew can you review these changes ?

**Comment by prashuchaudhary** [comment]
regarding the suggestion to denormalize the `labels.name` to subjects table, we will always
 be doing `like queries`. so it will also be relatively slow ??

**Comment by BenJam** [comment]
Same here @prashuchaudhary.

**Pull request closed without merging**
